export const translations = {
  en: {
    // Header
    books: "Books",
    aboutAuthor: "About the Author",
    contact: "Contact",
    readerDashboard: "Reader Dashboard",
    adminDashboard: "Admin Dashboard",
    login: "Login",
    register: "Register",
    // Footer
    quickLinks: "Quick Links",
    resources: "Resources",
    getInTouch: "Get in Touch",
    // Homepage
    featuredBooks: "Featured Books",
    awardsAndRecognition: "Awards & Recognition",
    inTheMedia: "In The Media",
    // Book Detail
    buyPrintBook: "Buy Print Book",
    readDigitalVersion: "Read Digital Version",
    aboutThisBook: "About this Book",
    // Reader
    exitReader: "Exit Reader",
    // User Dashboard
    myLibrary: "My Library",
    settings: "Settings",
    subscriptions: "My Subscriptions",
    // Admin Dashboard
    manageBooks: "Manage Books",
    uploadBook: "Upload Book",
    aiTools: "AI Tools",
    addBook: "Add New Book",
    editBook: "Edit Book",
    bookTitle: "Title",
    bookAuthor: "Author",
    coverImageUrl: "Cover Image URL",
    shortDescription: "Short Description",
    longDescription: "Long Description",
    amazonLink: "Amazon Link",
    awards: "Awards (comma-separated)",
    mediaMentions: "Media Mentions (format: source,link;source,link)",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    // Contact Page
    contactIntro: "Have a question, a comment, or a collaboration proposal? We'd love to hear from you. Fill out the form below or send us an email directly.",
    name: "Name",
    email: "Email",
    subject: "Subject",
    message: "Message",
    sendMessage: "Send Message",
    contactInformation: "Contact Information",
  },
  pt: {
    // Header
    books: "Livros",
    aboutAuthor: "Sobre o Autor",
    contact: "Contato",
    readerDashboard: "Painel do Leitor",
    adminDashboard: "Painel Admin",
    login: "Entrar",
    register: "Registrar",
    // Footer
    quickLinks: "Links Rápidos",
    resources: "Recursos",
    getInTouch: "Entre em Contato",
    // Homepage
    featuredBooks: "Livros em Destaque",
    awardsAndRecognition: "Prêmios e Reconhecimento",
    inTheMedia: "Na Mídia",
    // Book Detail
    buyPrintBook: "Comprar Livro Impresso",
    readDigitalVersion: "Ler Versão Digital",
    aboutThisBook: "Sobre este Livro",
    // Reader
    exitReader: "Sair do Leitor",
    // User Dashboard
    myLibrary: "Minha Biblioteca",
    settings: "Configurações",
    subscriptions: "Minhas Assinaturas",
    // Admin Dashboard
    manageBooks: "Gerenciar Livros",
    uploadBook: "Carregar Livro",
    aiTools: "Ferramentas de IA",
    addBook: "Adicionar Novo Livro",
    editBook: "Editar Livro",
    bookTitle: "Título",
    bookAuthor: "Autor",
    coverImageUrl: "URL da Imagem de Capa",
    shortDescription: "Descrição Curta",
    longDescription: "Descrição Longa",
    amazonLink: "Link da Amazon",
    awards: "Prêmios (separados por vírgula)",
    mediaMentions: "Menções na Mídia (formato: fonte,link;fonte,link)",
    saveChanges: "Salvar Alterações",
    cancel: "Cancelar",
    // Contact Page
    contactIntro: "Tem uma pergunta, um comentário ou uma proposta de colaboração? Adoraríamos ouvir de você. Preencha o formulário abaixo ou envie-nos um e-mail diretamente.",
    name: "Nome",
    email: "E-mail",
    subject: "Assunto",
    message: "Mensagem",
    sendMessage: "Enviar Mensagem",
    contactInformation: "Informações de Contato",
  },
};
